# Use config files to change parameters
expt_name: "time_now"
simLength: 50
random_activate: True
w_EE: 0.05
activate_strengthen_scale: 5.0
activate_weaken_scale: -1.0

w_II: 0.1
w_IE: 0.3

w_II_B: 0.0
w_IE_B: 0.0

seed: 3

